# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    update-manifest-stage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            repository: ashishworkspace/argo-cd-pipeline
            ref: 'master'
            token: ${{ secrets.PASSWORD }}
        - name: setup git config
          run: |
            git config --global user.email "ashishizofficial@gmail.com"
            git config --global user.name "Ashish Kumar"
            echo ${{ github.sha }}
            sed -i 's@image_name@'"${{ github.sha }}"'@' values.yaml
            git add -A
            git commit -am "Update image for - ${{ github.sha }}"
        - run: echo ${{ github }}
        - run: git push origin master
